#!/usr/bin/env python3
"""Generate deterministic SkillForge indexes from validated PASS objects."""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path

from validate import ObjectRecord, validate_ledgers, validate_library


BOOTSTRAP_OBJECT_ID = "AP_plan_and_build_work_from_thumbnail_to_final"
HEADER = "<!-- GENERATED by tools/build_index.py; do not hand-edit. -->\n"


def display(segment: str) -> str:
    return segment.replace("_", " ").replace("-", " ").title()


def object_sort_key(record: ObjectRecord) -> tuple[str, str]:
    return (str(record.data["name"]).casefold(), str(record.data["object_id"]))


def relative_link(from_directory: Path, target: Path) -> str:
    return target.relative_to(from_directory).as_posix()


def descendants_by_directory(records: list[ObjectRecord]) -> dict[tuple[str, ...], list[ObjectRecord]]:
    result: dict[tuple[str, ...], list[ObjectRecord]] = defaultdict(list)
    for record in records:
        parts = tuple(record.data["library_path"])
        for length in range(1, len(parts) + 1):
            result[parts[:length]].append(record)
    return result


def package_dependencies(records: list[ObjectRecord]) -> dict[str, set[str]]:
    by_id = {record.data["object_id"]: record for record in records}
    dependencies: dict[str, set[str]] = defaultdict(set)
    for record in records:
        source_package = record.data["library_path"][0]
        for link in record.data.get("cross_links", []):
            target = by_id.get(link["target_object_id"])
            if target:
                target_package = target.data["library_path"][0]
                if target_package != source_package:
                    dependencies[source_package].add(target_package)
    return dependencies


def render_root(records: list[ObjectRecord]) -> str:
    bootstrap = next((record for record in records if record.data["object_id"] == BOOTSTRAP_OBJECT_ID), None)
    if bootstrap is None or bootstrap.data["library_path"][0] != "metaskills":
        raise ValueError(f"required bootstrap object {BOOTSTRAP_OBJECT_ID} is missing from metaskills")
    packages = sorted(
        {record.data["library_path"][0] for record in records},
        key=lambda package: (package != "metaskills", package),
    )
    dependencies = package_dependencies(records)
    lines = [HEADER, "# SkillForge Library", "", "## Load First", "", f"- [{bootstrap.data['name']}]({bootstrap.relative_path.as_posix()}) - mandatory universal construction metaskill.", "", "## Packages", ""]
    for package in packages:
        count = sum(1 for record in records if record.data["library_path"][0] == package)
        requirement = "mandatory" if package == "metaskills" else "optional"
        dependency_text = ""
        if dependencies[package]:
            dependency_text = f" Requires: {', '.join(sorted(dependencies[package]))}."
        lines.append(f"- [{display(package)}]({package}/INDEX.md) - {requirement}; {count} object(s).{dependency_text}")
    lines.extend(["", "## Installation", "", "Install `metaskills` first, then copy only the package directories needed for the requested skill. Follow declared package dependencies before resolving cross-package links.", ""])
    return "\n".join(lines)


def reading_order_lines(scope_records: list[ObjectRecord]) -> list[str]:
    """Render a foundations-first reading order from prerequisite_for edges.

    Deterministic and link-free (names only) so it is stable across regeneration
    and correct at any directory depth. Shows each read-first root and the skills
    that build on it; empty when the scope has no prerequisite edges.
    """
    by_id = {record.data["object_id"]: record for record in scope_records}
    deps: dict[str, set[str]] = defaultdict(set)
    targets: set[str] = set()
    for record in scope_records:
        for link in record.data.get("cross_links", []):
            if link.get("rel") == "prerequisite_for" and link["target_object_id"] in by_id:
                deps[record.data["object_id"]].add(link["target_object_id"])
                targets.add(link["target_object_id"])
    roots = sorted((rid for rid in deps if rid not in targets), key=lambda rid: object_sort_key(by_id[rid]))
    if not roots:
        return []
    lines = ["## Reading order", "", "_Read a foundation before the skills that build on it (`prerequisite_for`)._", ""]
    for rid in roots:
        lines.append(f"- **{by_id[rid].data['name']}** — read first")
        for target in sorted(deps[rid], key=lambda t: object_sort_key(by_id[t])):
            lines.append(f"  - then: {by_id[target].data['name']}")
    lines.append("")
    return lines


def render_directory(directory_parts: tuple[str, ...], records: list[ObjectRecord], descendants: dict[tuple[str, ...], list[ObjectRecord]]) -> str:
    directory = Path(*directory_parts)
    direct_objects = sorted(
        (record for record in records if tuple(record.data["library_path"]) == directory_parts),
        key=object_sort_key,
    )
    child_parts = sorted(
        child for child in descendants
        if len(child) == len(directory_parts) + 1 and child[:-1] == directory_parts
    )
    title = " / ".join(display(part) for part in directory_parts)
    lines = [HEADER, f"# {title}", ""]
    lines.extend(reading_order_lines(descendants[directory_parts]))
    if child_parts:
        lines.extend(["## Topics", ""])
        for child in child_parts:
            count = len(descendants[child])
            lines.append(f"- [{display(child[-1])}]({child[-1]}/INDEX.md) - {count} object(s).")
        lines.append("")
    if direct_objects:
        lines.extend(["## Objects", ""])
        for record in direct_objects:
            filename = record.relative_path.name
            lines.append(f"- [{record.data['name']}]({filename}) - {record.data['object_type']}; {record.data['stage_binding']}.")
            variants = record.data.get("variants", [])
            if variants:
                names = ", ".join(f"`{variant['variant_name']}` ({variant['variant_basis']})" for variant in variants)
                lines.append(f"  - Variants: {names}.")
        lines.append("")
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def build_indexes(library_root: Path, ledger_root: Path) -> int:
    records = validate_library(library_root, ledger_root)
    errors = [(record.label, error) for record in records for error in record.errors]
    errors.extend((issue.label, issue.error) for issue in validate_ledgers(ledger_root))
    if errors:
        for label, error in errors:
            print(f"{label}: {error}")
        print("Refusing to generate indexes for an invalid library.")
        return 1
    descendants = descendants_by_directory(records)
    outputs: dict[Path, str] = {library_root / "INDEX.md": render_root(records)}
    for directory_parts in sorted(descendants):
        outputs[library_root.joinpath(*directory_parts) / "INDEX.md"] = render_directory(directory_parts, records, descendants)
    changed = sum(write_if_changed(path, content) for path, content in outputs.items())
    print(f"Generated {len(outputs)} index file(s); {changed} changed.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--library", type=Path, default=Path("library"))
    parser.add_argument("--ledger", type=Path, default=Path("ledger"))
    args = parser.parse_args()
    return build_indexes(args.library, args.ledger)


if __name__ == "__main__":
    raise SystemExit(main())
